### PR TITLE
#6: [stateParams] include Boolean parser by default (closes #6)

### LINKED ISSUE #6: [stateParams] include more parsers by default
## requirements

as discussed offline with @dhinus :
- boolean
- ~~number~~ (too tricky, see discussion at #7)
- ?
## specs

{optional: describe technical specs to implement this feature, if not obvious}
## misc

{optional: other useful info}

### PR DESCRIPTION
**Pull request by giogonzo**
Issue #6
### tests performed

{A Test Plan is used to show what you tested to make sure your code works fine. You should write here all that you did to test, and provide some results of your testing.

These results can be screenshots, query results, or even just pointers to unit tests that successfully passed.}
#### cross browser compatibility

{If applicable, please write on which browsers you tested this. A good test plan should include a few tests on different browsers among the supported ones.}
### tests not performed (domain coverage)

{At times not everything can be tested, and writing what hasn't been tested is just as important as writing what has been tested.

An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

**Comment by dhinus** [comment]
👍 for boolean.

Autoparsing integers has a few risks:
- could be an ID starting with `0` and you don't want to strip it
- could be a very long number bigger than [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), leading to weird results.

Example edge cases:

``` js
parseFloat("0123") //123

parseFloat("9999999999999999") //10000000000000000
parseInt("9999999999999999", 10) //10000000000000000
```

**Comment by giogonzo** [comment]
yup, this was supposed to be a temp fix to support webseed/tutorial but I found a problem similar to the first one on LOL:
`requestCode`s like `'12000333000'` <-- from regex perspective they are effectively numbers, but we want to threat them as strings (they are ids...)

IMO it doesn't make sense to go for a temporary solution (or we can just add `bool`, which looks more safer, and could allow for less boilerplate in webseed/tutorial)
and instead work on the more general one sketched in https://github.com/buildo/state-react-router/issues/3

**Comment by dhinus** [comment]
Can we please add boolean which looks safe and would be useful for webseed/tutorial?

**Comment by giogonzo** [comment]
yes. As discussed offline, that should be safe

**Comment by dhinus** [comment]
Renamed pull request and force-pushed new commit with the Boolean parser only.

**Comment by giogonzo** [comment]
nice 👍

**Pull request merged**
